### ISSUE TITLE
constant index.ts 변경 제안

### ISSUE THREAD

**Issue by StatPan** [leginote/assembly-ts#11]
/**
 * @description if you modify this properties, you should upgrade the minor version because it will be a break changes
 */
export const translatedVariableDictionary = {
  국회의원코드: 'lawmakerCode',
  국회의원명: 'lawmakerName',
  국회의원한자명: 'lawmakerChineseName',
  국회의원영문명: 'lawmakerEnglishName',
  생일구분코드: 'birthdayDivisionCode',
  생일일자: 'birthday',
  직책명: 'dutyName',
  정당명: 'politicalPartyName',
  선거구명: 'electoralDistrictName',
  선거구구분명: 'electoralDistrictDivisionName',
  위원회명: 'committeeName',
  소속위원회명: 'belongingCommitteeName',
  재선구분명: 're-electionClassificationDivision',  <--
  당선대수: 'GTELT_ERACO',   <-- 
  성별: 'gender',
  전화번호: 'phoneNumber',
  국회의원이메일주소: 'email',
  국회의원홈페이지URL: 'homepage',
  보좌관: 'aide',
  비서관: 'seniorSecretary',
  비서: 'secretary',
  약력: 'profile',
  사무실호실: 'officeRoom',
  사진: 'picture',
} as const;

위에 **재선구분명**과, **당선대수**가 우선 옥의티 같아서 다른 변수명 스타일과 비슷하게 가는거 어떤가요
재선구분명 -> reElectedDivisionName
당선대수 -> electedTerm

이거는 규칙화 해도 좋을 것 같아요
명 -> Name 
구분 -> Division

**Comment by sunrabbit123** [comment]
당선대수는 어떻게 표현해야할지 모르겠어서 일단은 API에 있던값 그대로 넣었던거고
재선구분명 수정도 좋네요

나중에 해당 내용 담아서 CONTRIBUTION.md 파일 생성하고
해당 내용들은 수정하는게 좋을 것 같네요

**Comment by sunrabbit123** [comment]
근데 당선대수가 electedTerm인가요
일단 `당선대수`라는 용어 자체도 구글링했을 때 안나와서 이게 뭔지 영
당선됐을 때의 대수인지 뭔지

**Comment by sunrabbit123** [comment]
당선대수의 경우 #13 으로 이전
