### ISSUE TITLE
`당선대수` - `GTELT_ERACO` 이름 공모

### ISSUE THREAD

**Issue by sunrabbit123** [leginote/assembly-ts#13]
해당 내용의 경우, 용어를 못찾아 아래와 같이 박제되어있음

```ts
export const translatedVariableDictionary = {
  국회의원코드: 'lawmakerCode',
  국회의원명: 'lawmakerName',
  국회의원한자명: 'lawmakerChineseName',
  국회의원영문명: 'lawmakerEnglishName',
  생일구분코드: 'birthdayDivisionCode',
  생일일자: 'birthday',
  직책명: 'dutyName',
  정당명: 'politicalPartyName',
  선거구명: 'electoralDistrictName',
  선거구구분명: 'electoralDistrictDivisionName',
  위원회명: 'committeeName',
  소속위원회명: 'belongingCommitteeName',
  재선구분명: 'reElectionClassificationDivision',
  당선대수: 'GTELT_ERACO', <--
  성별: 'gender',
  전화번호: 'phoneNumber',
  국회의원이메일주소: 'email',
  국회의원홈페이지URL: 'homepage',
  보좌관: 'aide',
  비서관: 'seniorSecretary',
  비서: 'secretary',
  약력: 'profile',
  사무실호실: 'officeRoom',
  사진: 'picture',
} as const;
```

**Comment by StatPan** [comment]
![image](https://github.com/user-attachments/assets/de21afb1-573b-42bf-aa9b-3eb87af40757)

![image](https://github.com/user-attachments/assets/522351e1-3a98-4573-b250-ff010d88810d)

일단 책자에 당선 내용 관련으로 있는 것으로
당선 의미는 election, victory가 유력한 것 같아요

![image](https://github.com/user-attachments/assets/3f87c8d9-c572-46ec-9648-c80452494e30)
위 그림으로 보면 election에 가까워지는 것 같고
https://dictionary.cambridge.org/ko/%EC%82%AC%EC%A0%84/%EC%98%81%EC%96%B4/election

당선 대수의 경우

미국은 어떻게 쓰는지 봤는데

![image](https://github.com/user-attachments/assets/67584058-4b69-4e78-af24-b39293ea9eee)


118대 국회 변수명에 대해서 congress로 쓰고 있네요

**Comment by sunrabbit123** [comment]
흠 그럼 당선대수가 당선되었을 때 국회 기수?를 이야기하는건가요

**Comment by sunrabbit123** [comment]
국회 기수 이야기하는거라면 electionCongress도 좋아보입니다

**Comment by StatPan** [comment]
대찬성입니다 당선대수는 그럼 electionCongress

**Comment by sunrabbit123** [comment]
#18 에서 마무리
