### ISSUE TITLE
docs: translatedVariableDiciontary 고도화

### ISSUE THREAD

**Issue by sunrabbit123** [leginote/assembly-ts#17]
각 프로퍼티 값끼리 겹치는 영역이 많아 오타 하나라도 나면 찾기 어려울 것 같으니
반복되는 용어들은 변수로 빼내어 템플릿 문법 이용하여 각 프로퍼티 값들을 이루도록 설정하는 것이 유지보수에 좋아보이네요

**Comment by StatPan** [comment]
각 단어별로 매핑해두고 변수명을 완성하는 느낌인가요?

  국회의원코드: `${prefixes.Lawmaker}${suffixes.Code}`,
  국회의원명: `${prefixes.Lawmaker}${suffixes.Name}`,
  국회의원한자명: `${prefixes.Lawmaker}Chinese${suffixes.Name}

요런식의?

우선 intellisense 동작하게 해두는게 확실히 필요하긴 한 것 같습니닷

**Comment by sunrabbit123** [comment]
네네 그런식입니다
intellisense 동작하게 해두는게 어떤 의미일까여(이해못함)

**Comment by StatPan** [comment]
아 말씀하신 의도랑 비슷하게, 직접 타이핑하는거 말구
변수에 . 찍으면 값 사용할 수 있게 만들면 좋겠어요

**Comment by sunrabbit123** [comment]
그거야 당연히 지원해야하는 내용인데
어디서 자동완성되는걸 이야기하는겁니까?

**Comment by StatPan** [comment]
음 단어들을 클래스 안에다 몰아넣어둘까요?
그럼 새로운 단체가 생겨도, 우리가 지정해둔 단어 조합을 조립해서 새로운 단어, 변수명을 만들 수 있게?
위 translation용 object 위치하는 곳에 별개 클래스로

**Comment by sunrabbit123** [comment]
일단 class로 굳이 뺄 이유가 없을 뿐더러
StatPan님이 이야기 하신 자동완성이 뭔 말인지 이해를 못했슴다

**Comment by sunrabbit123** [comment]
해당 이슈 내용대로 처리한다고 하더라도
기존 지원되던 자동완성에 문제는 안생기거든여

![image](https://github.com/user-attachments/assets/c2e126af-50e6-42e4-adf5-2bd47932ebca)

![image](https://github.com/user-attachments/assets/1339de8f-4ce2-4534-9f76-f0cfe441e71e)

**Comment by sunrabbit123** [comment]
@StatPan 초안 올렸어요
