### ISSUE TITLE
hotfix: organization profile image

### ISSUE THREAD

**Issue by sunrabbit123** [leginote/assembly-ts#9]
하와와 아무거나 이쁜것이면 좋다옵니다

**Comment by StatPan** [comment]
![image](https://github.com/user-attachments/assets/f6405859-9fd1-4d26-81ae-35fc60672dca)

![image](https://github.com/user-attachments/assets/20e34491-6b12-4116-8295-35154988b2a4)

![image](https://github.com/user-attachments/assets/09006ca5-0170-4737-885b-e8ce7758ec41)

![image](https://github.com/user-attachments/assets/718b18a1-0f47-4886-a2b4-673fd30c88cf)

![image](https://github.com/user-attachments/assets/3c68e1e2-573a-435d-92cb-1c56a6f7fee6)

![image](https://github.com/user-attachments/assets/e0861435-b382-470f-ac2b-e059336038f5)

**Comment by sunrabbit123** [comment]
GPT인가요

**Comment by sunrabbit123** [comment]
얘네 둘 마음에 드는데
두번째 사진은 검은색부분만 잘라서 써야할 듯 싶읍니다.

뭐가 좋으시죠

![image](https://github.com/user-attachments/assets/a1784731-5559-491e-9e31-3cc4d9157f0b)
![image](https://github.com/user-attachments/assets/5e8528e6-8b13-4498-af6a-3dd6bb1e4ddc)

**Comment by StatPan** [comment]
어 검은색 자르는거 귀찮을 것 같아서 그럼 1번이요 ㅋㅋ

**Comment by sunrabbit123** [comment]
수정완료
